### PR TITLE
Update to v1 and test

### PR DESCRIPTION
**Pull request by briochemc**
I'm not sure this has everything revised correctly, but I tried! I also re-added the `@mol` macro without the weight (which then is equal to `u"mol"` instead of grams).

### CODE REVIEW

**Comment by rafaqz** [comment]
Looks good to me!

**Comment by rafaqz** [comment]
There is also this: 
https://github.com/rafaqz/UnitfulConventionalMoles.jl

All the conventional molecular weights. Might be useful idk.

**Comment by briochemc** [comment]
> There is also this:
> https://github.com/rafaqz/UnitfulConventionalMoles.jl
> 
> All the conventional molecular weights. Might be useful idk.

Yes I saw it! It looks good too but I did no work on it because I don't have a need for it right now (I think I would only use `@mol` without the weight part.) 

---

Are you willing to register this package now or are there some other things to do first?

**Comment by rafaqz** [comment]
I'd have to try it a bit (you too) to be confident it's worth registering. I have too many packages now too.

**Comment by briochemc** [comment]
Is there any reason *not* to register it? I mean I think it is worth registering because I think it is useful already for anybody doing ratios of elements (or compounds). Expressing things directly in, e.g., `molN / molC` is really nicer than in `mol/mol` IMHO 😄. It's used a lot at least in marine biogeochemistry in which stoichiometric ratios are extensively studied/debated!

**Comment by rafaqz** [comment]
Mostly because I'm not sure the grams conversion part really makes sense, and I don't want to be responsible for answering questions about it! 

At least here it's just take-it-or-leave-it, instead of me actually endorsing it.

How about you use it for a while and see? We could even delete the complicated parts and register a simpler version.

**Pull request merged**
